### ISSUE TITLE
I get an error when saving options

### ISSUE THREAD

**Issue by andrearicci** [glutanimate/review-heatmap#101]
I get this popup whenever I try to change some preferences:

###Error

An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-11-14 15:03:03

Caught exception:
Traceback (most recent call last):
  File "C:\Users\andrea\AppData\Roaming\Anki2\addons21\review_heatmap\libaddon\gui\basic\dialog_basic.py", line 93, in accept
    self._onAccept()
  File "C:\Users\andrea\AppData\Roaming\Anki2\addons21\review_heatmap\libaddon\gui\dialog_options.py", line 130, in _onAccept
    self.config.save()
  File "C:\Users\andrea\AppData\Roaming\Anki2\addons21\review_heatmap\libaddon\anki\configmanager.py", line 216, in save
    saver(self._config[name])
  File "C:\Users\andrea\AppData\Roaming\Anki2\addons21\review_heatmap\libaddon\anki\configmanager.py", line 457, in _saveSynced
    self._getStorageObj("synced")[self._conf_key] = config
  File "anki\config.py", line 64, in __setitem__
  File "anki\config.py", line 40, in set
orjson.JSONEncodeError: Type is not JSON serializable: WrappedDict

**Comment by glutanimate** [comment]
Hi there,

It looks like you're using an older version of the add-on. Updating to the latest version should fix the issue. You can do so by following the download link at the top here: https://ankiweb.net/shared/info/1771074083
