### ISSUE TITLE
Addon only loading png icons

### ISSUE THREAD

**Issue by benedictdaske** [glutanimate/review-heatmap#147]
The addon is not loading the correct gui. Prior to this problem I manually fixed the "from collections.abc" import bug. Maybe the the are related somehow?
I already deactivated all other addons to make sure they're not causing the trouble...

![image](https://user-images.githubusercontent.com/70815437/163877293-3dfc8f99-46eb-4773-9595-0e57345f289c.png)

Furthermore, options tell me the following:

Caught exception:
Traceback (most recent call last):
  File "/home/bycolxxiv/.local/share/Anki2/addons21/review_heatmap/gui/options.py", line 217, in <lambda>
    options_action.triggered.connect(lambda _: invokeOptionsDialog())
  File "/home/bycolxxiv/.local/share/Anki2/addons21/review_heatmap/gui/options.py", line 209, in invokeOptionsDialog
    dialog = RevHmOptions(config, mw, parent=parent)
  File "/home/bycolxxiv/.local/share/Anki2/addons21/review_heatmap/gui/options.py", line 107, in __init__
    super(RevHmOptions, self).__init__(
  File "/home/bycolxxiv/.local/share/Anki2/addons21/review_heatmap/libaddon/gui/dialog_options.py", line 81, in __init__
    super(OptionsDialog, self).__init__(
  File "/home/bycolxxiv/.local/share/Anki2/addons21/review_heatmap/libaddon/gui/basic/dialog_mapped.py", line 154, in __init__
    self.setData(data)
  File "/home/bycolxxiv/.local/share/Anki2/addons21/review_heatmap/libaddon/gui/basic/dialog_mapped.py", line 162, in setData
    self.interface.set(widget_name, key, value)
  File "/home/bycolxxiv/.local/share/Anki2/addons21/review_heatmap/libaddon/gui/basic/interface.py", line 271, in set
    return setter(widget, data)
  File "/home/bycolxxiv/.local/share/Anki2/addons21/review_heatmap/libaddon/gui/basic/interface.py", line 355, in setValue
    self._setDateTime(widget, data)
  File "/home/bycolxxiv/.local/share/Anki2/addons21/review_heatmap/libaddon/gui/basic/interface.py", line 801, in _setDateTime
    return qdatetimeedit.setDateTime(self._createDateTimeFromUnix(curtime))
  File "/home/bycolxxiv/.local/share/Anki2/addons21/review_heatmap/libaddon/gui/basic/interface.py", line 794, in _createDateTimeFromUnix
    qdatetime.setTime_t(unixtime)
AttributeError: 'QDateTime' object has no attribute 'setTime_t'

Thanks a lot in advance!

**Comment by LiYuxuanhaha** [comment]
I had the same problem

To solve the problem. You can change your anki to Qt5 version.

**Comment by benedictdaske** [comment]
Thanks, that worked for me too!

**Comment by ljredux** [comment]
Good to know there is a solution (thanks LiYuxuanhaha) even though it's... suboptimal for those of using Chocolatey to keep our third party software up to date.  Hopefully it will sort itself out sooner rather than later.

**Comment by glutanimate** [comment]
Hey guys,

Thanks for the report! This should be fixed with v1.0.0 which I just released on AnkiWeb: https://ankiweb.net/shared/info/1771074083 (no need for a manual installation any more, you can just copy the add-on code into Anki as with other add-ons.)

If you run into any issues please do let me know!

(cf. #136)
