### ISSUE TITLE
help on review heatmap

### ISSUE THREAD

**Issue by nicogallo1** [glutanimate/review-heatmap#150]
Hello, please im having problems with the heatmap. nothing appears.
<img width="483" alt="Captura de Pantalla 2022-05-11 a la(s) 11 08 31" src="https://user-images.githubusercontent.com/105370661/167870054-eec0a209-f4b9-4c56-887f-b9c4f648524e.png">
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [x] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.51 (cf78a555) Python 3.9.7 Qt 6.2.3 PyQt 6.2.3
Platform: Mac 12.3.1
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-05-11 10:28:54
Add-ons possibly involved: ⁨Review Heatmap⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/nicolasgallo/Library/Application Support/Anki2/addons21/review_heatmap/gui/options.py", line 217, in <lambda>
    options_action.triggered.connect(lambda _: invokeOptionsDialog())
  File "/Users/nicolasgallo/Library/Application Support/Anki2/addons21/review_heatmap/gui/options.py", line 209, in invokeOptionsDialog
    dialog = RevHmOptions(config, mw, parent=parent)
  File "/Users/nicolasgallo/Library/Application Support/Anki2/addons21/review_heatmap/gui/options.py", line 107, in __init__
    super(RevHmOptions, self).__init__(
  File "/Users/nicolasgallo/Library/Application Support/Anki2/addons21/review_heatmap/libaddon/gui/dialog_options.py", line 81, in __init__
    super(OptionsDialog, self).__init__(
  File "/Users/nicolasgallo/Library/Application Support/Anki2/addons21/review_heatmap/libaddon/gui/basic/dialog_mapped.py", line 154, in __init__
    self.setData(data)
  File "/Users/nicolasgallo/Library/Application Support/Anki2/addons21/review_heatmap/libaddon/gui/basic/dialog_mapped.py", line 162, in setData
    self.interface.set(widget_name, key, value)
  File "/Users/nicolasgallo/Library/Application Support/Anki2/addons21/review_heatmap/libaddon/gui/basic/interface.py", line 270, in set
    return setter(widget, data)
  File "/Users/nicolasgallo/Library/Application Support/Anki2/addons21/review_heatmap/libaddon/gui/basic/interface.py", line 354, in setValue
    self._setDateTime(widget, data)
  File "/Users/nicolasgallo/Library/Application Support/Anki2/addons21/review_heatmap/libaddon/gui/basic/interface.py", line 800, in _setDateTime
    return qdatetimeedit.setDateTime(self._createDateTimeFromUnix(curtime))
  File "/Users/nicolasgallo/Library/Application Support/Anki2/addons21/review_heatmap/libaddon/gui/basic/interface.py", line 793, in _createDateTimeFromUnix
    qdatetime.setTime_t(unixtime)
AttributeError: 'QDateTime' object has no attribute 'setTime_t'

```

```

```

**Comment by glutanimate** [comment]
Hey nicogallo, thanks for the report! This should be fixed with v1.0.0 which I just released on AnkiWeb: https://ankiweb.net/shared/info/1771074083

(So no need to install manually by downloading the .ankiaddon file any more. You can just copy the add-on code into Anki as with other add-ons.)

If you run into any issues please do let me know!

(cf. #136)
