### ISSUE TITLE
Can't work and show an error message

### ISSUE THREAD

**Issue by purequant** [glutanimate/review-heatmap#158]
#### Problem description

*Only this add-on is enable, but it can't work.*

>  Error
> An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
> If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
> When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
> Debug info:
> Anki 2.1.52 (ab1c2395) Python 3.9.7 Qt 5.15.2 PyQt 5.15.5
> Platform: Windows 10
> Flags: frz=True ao=True sv=3
> Add-ons, last update check: 2022-05-23 14:17:44
> 
> Traceback (most recent call last):
>   File "aqt.main", line 573, in loadCollection
>   File "aqt.main", line 672, in moveToState
>   File "aqt.main", line 678, in _deckBrowserState
>   File "aqt.deckbrowser", line 69, in show
>   File "aqt.deckbrowser", line 144, in _renderPage
>   File "aqt.deckbrowser", line 153, in __renderPage
>   File "aqt.hooks_gen", line 1444, in __call__
>   File "D:\AnkiDataFolder\addons21\1771074083\views.py", line 81, in on_deckbrowser_will_render_content
>     heatmap_html = self._controller.render_for_view(self._view)
>   File "D:\AnkiDataFolder\addons21\1771074083\controller.py", line 77, in render_for_view
>     return self._renderer.render(view, limhist, limfcst, current_deck_only)
>   File "D:\AnkiDataFolder\addons21\1771074083\renderer.py", line 152, in render
>     report = self._reporter.get_report(
>   File "D:\AnkiDataFolder\addons21\1771074083\activity.py", line 134, in get_report
>     history = self._cards_done(
>   File "D:\AnkiDataFolder\addons21\1771074083\activity.py", line 471, in _cards_done
>     deck_limit = self._revlog_limit(current_deck_only)
>   File "D:\AnkiDataFolder\addons21\1771074083\activity.py", line 374, in _revlog_limit
>     dids = self._valid_decks(excluded_dids)
>   File "D:\AnkiDataFolder\addons21\1771074083\activity.py", line 351, in _valid_decks
>     children = [d[1] for d in self._col.decks.children(did)]
>   File "anki.decks", line 460, in children
>   File "anki.decks", line 453, in deck_and_child_name_ids
>   File "anki._backend.generated", line 454, in get_deck_and_child_names
>   File "anki._backend", line 146, in _run_command
> anki.errors.NotFoundError

**Comment by glutanimate** [comment]
Hey purequant,

Thanks for the report! A fix for this will be in v1.0.0 (see #156).

If you have time, I would appreciate it if you could give the [test build](https://github.com/glutanimate/temp-workspace/releases/download/0.0.1/review-heatmap-v1.0.0-12-g2f83c3e-rh156-qt5+qt6-ankiweb.ankiaddon) a try and let me know if it fixes the problem for you. Thanks!

**Comment by purequant** [comment]
Thanks, the test build version works well for me.


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
22/05/23
21:45:09

Aristotelis ***@***.***> 于2022年5月23日周一 21:27写道：
