### ISSUE TITLE
Heatmap doesn't work after upgrading to 2.1.54

### ISSUE THREAD

**Issue by chribbex** [glutanimate/review-heatmap#167]
The heatmap is replaced by some icons after updating Anki.

<img width="764" alt="Screenshot 2022-06-29 at 09 36 12" src="https://user-images.githubusercontent.com/54573621/176379395-f929cd7d-25af-429e-bd21-f6fbfa0b298f.png">

Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Mac 12.4
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-06-29 09:25:54
Add-ons possibly involved: ⁨Review Heatmap⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.addons", line 962, in onConfig
  File "/Users/user/Library/Application Support/Anki2/addons21/review_heatmap/gui/options.py", line 209, in invokeOptionsDialog
    dialog = RevHmOptions(config, mw, parent=parent)
  File "/Users/user/Library/Application Support/Anki2/addons21/review_heatmap/gui/options.py", line 107, in __init__
    super(RevHmOptions, self).__init__(
  File "/Users/user/Library/Application Support/Anki2/addons21/review_heatmap/libaddon/gui/dialog_options.py", line 81, in __init__
    super(OptionsDialog, self).__init__(
  File "/Users/user/Library/Application Support/Anki2/addons21/review_heatmap/libaddon/gui/basic/dialog_mapped.py", line 154, in __init__
    self.setData(data)
  File "/Users/user/Library/Application Support/Anki2/addons21/review_heatmap/libaddon/gui/basic/dialog_mapped.py", line 162, in setData
    self.interface.set(widget_name, key, value)
  File "/Users/user/Library/Application Support/Anki2/addons21/review_heatmap/libaddon/gui/basic/interface.py", line 270, in set
    return setter(widget, data)
  File "/Users/user/Library/Application Support/Anki2/addons21/review_heatmap/libaddon/gui/basic/interface.py", line 354, in setValue
    self._setDateTime(widget, data)
  File "/Users/user/Library/Application Support/Anki2/addons21/review_heatmap/libaddon/gui/basic/interface.py", line 800, in _setDateTime
    return qdatetimeedit.setDateTime(self._createDateTimeFromUnix(curtime))
  File "/Users/user/Library/Application Support/Anki2/addons21/review_heatmap/libaddon/gui/basic/interface.py", line 793, in _createDateTimeFromUnix
    qdatetime.setTime_t(unixtime)
AttributeError: 'QDateTime' object has no attribute 'setTime_t'

**Comment by glutanimate** [comment]
Hi, it looks like you’re using an old version of the add-on. Please update to the latest one by installing from AnkiWeb: https://ankiweb.net/shared/info/1771074083
