### ISSUE TITLE
Not working in Anki 2.1.57 (6b7d372c)⁩

### ISSUE THREAD

**Issue by markhavemann** [Glutanimate/review-heatmap#181]
#### Problem description

*Not working in Anki 2.1.57 (6b7d372c)⁩
On the main page it just displays broken image link icons:
![image](https://user-images.githubusercontent.com/2283022/217708288-a9efa941-faba-4218-b409-1e68a422c2b3.png)

When I go to the addons menu and click the "config" button for review heatmap I get the following error:

Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.57 (6b7d372c) Python 3.9.15 Qt 6.4.2 PyQt 6.4.0
Platform: Windows-10-10.0.19041
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-02-09 11:06:47

Caught exception:
Traceback (most recent call last):
  File "aqt.addons", line 971, in onConfig
  File "C:\Users\Mark\AppData\Roaming\Anki2\addons21\review_heatmap\gui\options.py", line 209, in invokeOptionsDialog
    dialog = RevHmOptions(config, mw, parent=parent)
  File "C:\Users\Mark\AppData\Roaming\Anki2\addons21\review_heatmap\gui\options.py", line 107, in __init__
    super(RevHmOptions, self).__init__(
  File "C:\Users\Mark\AppData\Roaming\Anki2\addons21\review_heatmap\libaddon\gui\dialog_options.py", line 81, in __init__
    super(OptionsDialog, self).__init__(
  File "C:\Users\Mark\AppData\Roaming\Anki2\addons21\review_heatmap\libaddon\gui\basic\dialog_mapped.py", line 154, in __init__
    self.setData(data)
  File "C:\Users\Mark\AppData\Roaming\Anki2\addons21\review_heatmap\libaddon\gui\basic\dialog_mapped.py", line 162, in setData
    self.interface.set(widget_name, key, value)
  File "C:\Users\Mark\AppData\Roaming\Anki2\addons21\review_heatmap\libaddon\gui\basic\interface.py", line 270, in set
    return setter(widget, data)
  File "C:\Users\Mark\AppData\Roaming\Anki2\addons21\review_heatmap\libaddon\gui\basic\interface.py", line 354, in setValue
    self._setDateTime(widget, data)
  File "C:\Users\Mark\AppData\Roaming\Anki2\addons21\review_heatmap\libaddon\gui\basic\interface.py", line 800, in _setDateTime
    return qdatetimeedit.setDateTime(self._createDateTimeFromUnix(curtime))
  File "C:\Users\Mark\AppData\Roaming\Anki2\addons21\review_heatmap\libaddon\gui\basic\interface.py", line 793, in _createDateTimeFromUnix
    qdatetime.setTime_t(unixtime)
AttributeError: 'QDateTime' object has no attribute 'setTime_t'

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [ ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```

```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python

```

**Comment by glutanimate** [comment]
Hey Mark, thanks for the report! It looks like you have an older version of the add-on installed. Please delete the one you currently have installed and download the latest release from [AnkiWeb](https://ankiweb.net/shared/info/1771074083). That should fix the missing heatmap :)

**Comment by markhavemann** [comment]
Thank you!
