### ISSUE TITLE
Erro na Extensão

### ISSUE THREAD

**Issue by SthefanneJordany** [Glutanimate/review-heatmap#190]
#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 6.6.0 PyQt 6.6.0
Platform: Windows-10-10.0.19041
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-12-12 07:36:41

When loading Review Heatmap:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "C:\Users\Sthefanne Jordany\AppData\Roaming\Anki2\addons21\review_heatmap\__init__.py", line 124, in <module>
    initializeAddon()
  File "C:\Users\Sthefanne Jordany\AppData\Roaming\Anki2\addons21\review_heatmap\__init__.py", line 114, in initializeAddon
    from .gui.options import initializeOptions
  File "C:\Users\Sthefanne Jordany\AppData\Roaming\Anki2\addons21\review_heatmap\gui\options.py", line 44, in <module>
    from ..libaddon.gui.dialog_options import OptionsDialog
  File "C:\Users\Sthefanne Jordany\AppData\Roaming\Anki2\addons21\review_heatmap\libaddon\gui\dialog_options.py", line 48, in <module>
    from .basic.dialog_mapped import MappedDialog
  File "C:\Users\Sthefanne Jordany\AppData\Roaming\Anki2\addons21\review_heatmap\libaddon\gui\basic\dialog_mapped.py", line 42, in <module>
    from .widgets.qt import *
  File "C:\Users\Sthefanne Jordany\AppData\Roaming\Anki2\addons21\review_heatmap\libaddon\gui\basic\widgets\qt.py", line 41, in <module>
    import sip
ModuleNotFoundError: No module named 'sip'

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ ] I've restarted Anki to see if it helps
 - [ ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ ] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [ ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [ ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```

```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python

```

**Comment by glutanimate** [comment]
Hi there, it looks like you're using an older version of the add-on. Please uninstall it under _Tools_ → _Add-ons_ (on Anki's main screen), and then download the new version from [AnkiWeb](https://ankiweb.net/shared/info/1771074083).

-----

Olá, parece que você está usando uma versão antiga do complemento. Desinstale-o em _Tools_ → _Add-ons_ (na tela principal do Anki) e, em seguida, baixe a nova versão em [AnkiWeb](https://ankiweb.net/shared/info/1771074083).
