### ISSUE TITLE
bug when clicking green check boxes on home screen

### ISSUE THREAD

**Issue by chillysauce5** [glutanimate/review-heatmap#63]
#### Problem description

Just clicked on one of the boxes on the home page and when i entered it spat the error at me. 

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [x] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

2.1.20

##### If you are using Anki 2.1

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.20 (47a1bf8b) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-03-08 21:37:39

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 30, in cmd
  File "aqt\webview.py", line 96, in _onCmd
  File "aqt\webview.py", line 422, in _onBridgeCmd
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-24>", line 2, in _linkHandler
  File "lib\site-packages\anki\hooks.py", line 530, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 527, in repl
  File "C:\Users\patri\AppData\Roaming\Anki2\addons21\review_heatmap\links.py", line 86, in heatmapLinkHandler
    invokeBrowser(arg)
  File "C:\Users\patri\AppData\Roaming\Anki2\addons21\review_heatmap\links.py", line 112, in invokeBrowser
    browser.onSearchActivated()
  File "aqt\browser.py", line 749, in onSearchActivated
  File "aqt\editor.py", line 442, in saveNow
  File "aqt\editor.py", line 542, in saveTags
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-4>", line 2, in flush
  File "lib\site-packages\anki\hooks.py", line 530, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 522, in repl
  File "C:\Users\patri\AppData\Roaming\Anki2\addons21\865767531\__init__.py", line 173, in update_caches_for_note
    self.add_cards_to_caches(s.col, [card.id for card in s.cards()], update=True)
  File "C:\Users\patri\AppData\Roaming\Anki2\addons21\865767531\__init__.py", line 99, in add_cards_to_caches
    qa = card._getQA()
AttributeError: 'Card' object has no attribute '_getQA'

```

#####  If you are using Anki 2.0

*__ONLY IF YOU ARE USING ANKI 2.0__: Please open Anki, go to Help → About, find the two lines starting with `Version:` and `Qt`, and copy-paste them between the backticks below:*

```

```

*Please fill in details about your operating system (Windows/macOS/Linux, which version):*

- OS: windows 10
- version: 1909

*Please open Anki, go to Tools → Add-ons, take a screenshot of your installed add-ons, and paste it below:*

![image](https://user-images.githubusercontent.com/9625211/76171846-a9794e00-6187-11ea-935b-0be7ae9e2ba6.png)

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.20 (47a1bf8b) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-03-08 21:37:39

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 30, in cmd
  File "aqt\webview.py", line 96, in _onCmd
  File "aqt\webview.py", line 422, in _onBridgeCmd
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-24>", line 2, in _linkHandler
  File "lib\site-packages\anki\hooks.py", line 530, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 527, in repl
  File "C:\Users\patri\AppData\Roaming\Anki2\addons21\review_heatmap\links.py", line 86, in heatmapLinkHandler
    invokeBrowser(arg)
  File "C:\Users\patri\AppData\Roaming\Anki2\addons21\review_heatmap\links.py", line 112, in invokeBrowser
    browser.onSearchActivated()
  File "aqt\browser.py", line 749, in onSearchActivated
  File "aqt\editor.py", line 442, in saveNow
  File "aqt\editor.py", line 542, in saveTags
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-4>", line 2, in flush
  File "lib\site-packages\anki\hooks.py", line 530, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 522, in repl
  File "C:\Users\patri\AppData\Roaming\Anki2\addons21\865767531\__init__.py", line 173, in update_caches_for_note
    self.add_cards_to_caches(s.col, [card.id for card in s.cards()], update=True)
  File "C:\Users\patri\AppData\Roaming\Anki2\addons21\865767531\__init__.py", line 99, in add_cards_to_caches
    qa = card._getQA()
AttributeError: 'Card' object has no attribute '_getQA'

```

**Comment by chillysauce5** [comment]
sorted. problem was another addon iirc
