### ISSUE TITLE
won't change color

### ISSUE THREAD

**Issue by papigordo** [glutanimate/review-heatmap#79]
#### Problem description

just loaded on review heat map and was trying to change the color from lime to ice and also happened with magenta and I get this popup error when I try to click ok

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've restarted Anki to see if it helps
 - [x ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [ ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [ ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```
    
    Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
    Platform: Mac 10.15.5
    Flags: frz=True ao=True sv=1
    Add-ons, last update check: 2020-06-14 23:26:20
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    AMBOSS add-on ['0amboss_addon', 2020-05-26T11:47, 'None', '']
    Advanced Browser ['874215009', 2020-04-22T18:45, 'None', '']
    Anki Zoom ['538879081', 2020-04-03T20:20, 'v1.1.3', mod]
    Batch Editing ['291119185', 2019-06-02T14:47, 'None', '']
    Dancing Baloney Allows changing wallpapers with live preview ['378638814', 2020-03-27T01:28, 'None', mod]
    Frozen Fields ['516643804', 2020-02-29T23:12, 'None', '']
    Hierarchical Tags 2 ['594329229', 2020-04-11T12:36, 'None', '']
    Highlight Search Results in the Browser ['225180905', 2018-02-16T19:40, 'None', '']
    ImageResizer ['1214357311', 2018-09-09T21:17, 'None', '']
    More Overview Stats ['2116130837', 2020-02-17T11:01, 'None', '']
    No Distractions Full Screen Clean review interface  TabletTouch support ['1049863218', 2020-04-25T21:47, 'v4.1.6', mod]
    Puppy Reinforcement ['puppy_reinforcer', 0, 'None', '']
    Review Heatmap ['review_heatmap', 2018-10-28T18:06, 'None', '']
    load balancer ['1417170896', 2020-02-17T15:02, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1049863218 1214357311 1417170896 2116130837 225180905 291119185 378638814 516643804 538879081 594329229 874215009
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    

```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.15.5
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-06-14 23:26:20
Add-ons possibly involved: ⁨Review Heatmap⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/papigordo/Library/Application Support/Anki2/addons21/review_heatmap/libaddon/gui/basic/dialog_basic.py", line 93, in accept
    self._onAccept()
  File "/Users/papigordo/Library/Application Support/Anki2/addons21/review_heatmap/libaddon/gui/dialog_options.py", line 130, in _onAccept
    self.config.save()
  File "/Users/papigordo/Library/Application Support/Anki2/addons21/review_heatmap/libaddon/anki/configmanager.py", line 216, in save
    saver(self._config[name])
  File "/Users/papigordo/Library/Application Support/Anki2/addons21/review_heatmap/libaddon/anki/configmanager.py", line 457, in _saveSynced
    self._getStorageObj("synced")[self._conf_key] = config
  File "anki/config.py", line 60, in __setitem__
  File "anki/config.py", line 36, in set
  File "anki/rsbackend.py", line 591, in set_config_json
orjson.JSONEncodeError: Type is not JSON serializable: WrappedDict

```

**Comment by papigordo** [comment]
just to add to this ... the color did change to ice after having closed the error message and the review heat map options page and went to copy the debug info, however after restarting Anki the color has gone back to lime and the issue persists 

than you for all the work you've put into this!

**Comment by glutanimate** [comment]
Hi there,

Thanks for the detailed bug report! Please download the latest version of the add-on by following the download link at the top here: https://ankiweb.net/shared/info/1771074083

That should fix the error message.
