### ISSUE TITLE
Not able to configure add-on in Anki 2.1.30

### ISSUE THREAD

**Issue by Clintobi** [glutanimate/review-heatmap#92]
Whenever I try to customize the add-on and click the "OK" button, I get the following Debug info:
Anki 2.1.30 (06a69c25) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-08-27 12:32:02

Caught exception:
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Anki2\addons21\review_heatmap\libaddon\gui\basic\dialog_basic.py", line 93, in accept
    self._onAccept()
  File "C:\Users\USER\AppData\Roaming\Anki2\addons21\review_heatmap\libaddon\gui\dialog_options.py", line 130, in _onAccept
    self.config.save()
  File "C:\Users\USER\AppData\Roaming\Anki2\addons21\review_heatmap\libaddon\anki\configmanager.py", line 216, in save
    saver(self._config[name])
  File "C:\Users\USER\AppData\Roaming\Anki2\addons21\review_heatmap\libaddon\anki\configmanager.py", line 457, in _saveSynced
    self._getStorageObj("synced")[self._conf_key] = config
  File "anki\config.py", line 64, in __setitem__
  File "anki\config.py", line 40, in set
orjson.JSONEncodeError: Type is not JSON serializable: WrappedDict

The issue has been existing since I upgraded to 2.1.30 from 2.1.22

**Comment by glutanimate** [comment]
Hi there,

It looks like you're using an old version of the add-on. If you upgrade to the latest revision that should get rid of the error message. You can grab the latest download right at the top here: https://ankiweb.net/shared/info/1771074083

Hope that helps!

(cf. #79)
