### ISSUE TITLE
Changing the colour of the heatmap doesnt work

### ISSUE THREAD

**Issue by marscookies** [glutanimate/review-heatmap#94]
Hi, I have a slight struggle with changing the colour from the default to flame like Ive had it before. For some reason, it doesn't work anymore since I made the update to Anki 2.33.

Following message appears when I want to change it in the settings.

Error
[...]
Debug info:
Anki 2.1.33 (3f403040) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-09-04 18:24:24

Caught exception:
Traceback (most recent call last):
  File "C:\Users\l\AppData\Roaming\Anki2\addons21\review_heatmap\libaddon\gui\basic\dialog_basic.py", line 93, in accept
    self._onAccept()
  File "C:\Users\l\AppData\Roaming\Anki2\addons21\review_heatmap\libaddon\gui\dialog_options.py", line 130, in _onAccept
    self.config.save()
  File "C:\Users\l\AppData\Roaming\Anki2\addons21\review_heatmap\libaddon\anki\configmanager.py", line 216, in save
    saver(self._config[name])
  File "C:\Users\l\AppData\Roaming\Anki2\addons21\review_heatmap\libaddon\anki\configmanager.py", line 457, in _saveSynced
    self._getStorageObj("synced")[self._conf_key] = config
  File "anki\config.py", line 64, in __setitem__
  File "anki\config.py", line 40, in set
orjson.JSONEncodeError: Type is not JSON serializable: WrappedDict

I tried disabling all other addons I have, but the same message occurred. 

Does anyone by any chance have a similar problem and could help me resolve it?

**Comment by glutanimate** [comment]
Hi marscookies,

Please update to the latest version of the add-on by downloading it at the top here: https://ankiweb.net/shared/info/1771074083

Hope that helps

(cf. #79 )

**Comment by marscookies** [comment]
It did! thanks :)
